### PR TITLE
Add documentation for version 7.1

### PR DESCRIPTION
**Pull request by pingyu**
### What is changed?

- Add docs for LTS version 7.1:
  - Overall, version list on the top: https://deploy-preview-349--tikv.netlify.app/
  - Release notes for 7.1: https://deploy-preview-349--tikv.netlify.app/docs/7.1/new-features/overview/
  - Release notes for dev: https://deploy-preview-349--tikv.netlify.app/docs/dev/new-features/overview/ (currently nothing)
- Add guide about how a add a new release 
  Preview: https://github.com/pingyu/tikv-website/blob/add-version-7.1/CONTRIBUTING.md#add-a-version

### Which version does your change affect?

v7.1, dev

### CODE REVIEW

**Comment by iosmanthus** [comment]
Pretty cool! Are the release-7.1 docs ported from the older version?

**Comment by pingyu** [comment]
> Pretty cool! Are the release-7.1 docs ported from the older version?

Mostly copy from `dev`, except for release notes.

**Comment by pingyu** [comment]
cc @zeminzhou PTAL~

**Review by zeminzhou — APPROVED** [review]
LGTM～

**Pull request merged**
