### PR TITLE
blog: add docs quest post

### PR DESCRIPTION
**Pull request by nrc**
PTAL @WT-Liu @dcalvin 

Please make live on Monday morning (China time)

### CODE REVIEW

**Review by dcalvin — APPROVED** [review]
Look great to me. I can't wait to see what comes out of it! Thanks @nrc. This is exciting.

**Comment by nrc** [comment]
@WT-Liu is it ok to publish this today?

**Review by WT-Liu — APPROVED** [review]

**Comment by WT-Liu** [comment]
@nrc Yes! Let's publish it today!

**Comment by WT-Liu** [comment]
@nrc The preview shows the two pictures fail to be loaded. Will you check them again?

**Comment by nrc** [comment]
@WT-Liu it should work now, I'm not exactly sure the path rules that Hugo uses, but I think I have it right.

**Comment by WT-Liu** [comment]
@nrc It works now! Thanks!

**Pull request merged**
