### PR TITLE
Overhaul menus

### PR DESCRIPTION
**Pull request by Hoverbear**
This overhauls the entire menu system as well as moving Deep dive into docs. I highly recommend building it and testing over trying to do manual code review.

This uses the `menu` system hugo has: https://gohugo.io/variables/menus/

It's not amazing, but it's a bit more clean than we have right now.

**Note this breaks existing Deep Dive Links**

### CODE REVIEW

**Comment by dcalvin** [comment]
@Hoverbear I had a run locally and it looked great. The only comment is the Roman numbers - Can we remove them? In documentation, numbers denote sequential steps, which is not necessarily the relations between the topics. What do you think?

**Comment by lucperkins** [comment]
I'm okay with these changes in general, but the new docs nav could use some work on mobile:

Screen Shot 2019-07-05 at 10 04 07 AM

**Comment by Hoverbear** [comment]
@lucperkins Whoa! Good catch! Let me fix that. :)

**Comment by Hoverbear** [comment]
How's this?

image

**Comment by dcalvin** [comment]
> How's this?
> 
> image

This looks perfect!

**Pull request merged**
