### PR TITLE
Add multi-version support

### PR DESCRIPTION
**Pull request by Hoverbear**
Add multi-version support to website. It's important since we'll soon be posting 3.1/4.0 etc.

This also restructures our menus!

Here's a preview!

image
image

Note: No awkward tabs in the hero!

Some notes: 

* The top menu is restructured, partially to give better accessibility and partially to give more flexibility so that if a user selects the non-default version of TiKV they can consistently stay on that version so long as they remain in the documentation sections of the site.
* The Side menu has a much nicer visual appearance now
* Linking schemes should remain consistent.
* Some minor page movement occurred. They're not ultra-popular pages so it's safe to just let search engines rediscover them
* Versions are expected to be fairly normal (3.1.0, 4.0.0, 4.0-beta, etc)
* There's some hacks to get this to work because Hugo isn't very flexible.

Future work will be: 
* Improve version selector
* Teach Google not to return results for older versions unless asked. (See canonical pages etc)

### CODE REVIEW

**Comment by dcalvin** [comment]
Bulma Menus looks cool!!!

**Comment by dcalvin** [comment]
Also is there any feature or content specific to 3.1 beta?

**Comment by Hoverbear** [comment]
Not at the moment!

We've published 3.1.0-beta though so it makes sense for it to be present and evolve into 3.1 itself. Things we need to add:

* More monitoring docs (#111)
* Docs about follower read
* Docs about pprof
* Docs about backup/restore

**Comment by Hoverbear** [comment]
Using the Bulma menu styles now:

image

**Comment by dcalvin** [comment]
Looking at the preview of Bulma version, I have some questions:
- On the horizontal menu, should we lay out the subsections of documentation? This makes the whole site look like a documentation side. Normally these subsections should be under one Doc tab. 
- Can we support folding/unfolding the navigation TOC on the left after we enter the doc? It looks more comfortable in style, but just is too long when all of subsections are in listed together. 
- Can we support in-page TOC on the right?

**Comment by Hoverbear** [comment]
> Looking at the preview of Bulma version, 

Bulma is the CSS framework @lucperkins used to create the TiKV site, it's some piece of tech backing our menus, it's the overall look at feel of our entire site. :)

> On the horizontal menu, should we lay out the subsections of documentation? This makes the whole site look like a documentation side. Normally these subsections should be under one Doc tab.

I rather like this way, but if you'd prefer we can collapse them. I did collapse the menus on mobile :)

> Can we support folding/unfolding the navigation TOC on the left after we enter the doc? It looks more comfortable in style, but just is too long when all of subsections are in listed together.

Bulma doesn't support this out of the box. I might be able to hack on it a bit to add this feature. :)

> Can we support in-page TOC on the right?

Apparently Hugo does generate a TOC so maybe (https://gohugo.io/content-management/toc/)! I feel like this is outside of the scope of this PR though?

**Comment by Hoverbear** [comment]
> On the horizontal menu, should we lay out the subsections of documentation? This makes the whole site look like a documentation side. Normally these subsections should be under one Doc tab.

Fixed :)

**Comment by dcalvin** [comment]
> > On the horizontal menu, should we lay out the subsections of documentation? This makes the whole site look like a documentation side. Normally these subsections should be under one Doc tab.
> 
> Fixed :)
Thanks. Some further comments:
- The text font on the left navigation do not look so distinguishable between different levels of titles.  
- The left navigation is not so responsive if I use the top navigation under docs, for example, If I select Reference, the left navigation does not auto scroll down to the corresponding position.  It has to be scrolled down manually.
- It could be better if we could collapse the left navigation bar by default and make it more responsive. But if not, I prefer our previous layout (using horizontal navigation tabs)

**Comment by Hoverbear** [comment]
Sounds like you're unsatisfied with Bulma's menus! I am too! I'm going to build some menus with something else and we can evaluate that. :)

**Comment by Hoverbear** [comment]
@dcalvin Can you have a try with https://deploy-preview-114--tikv.netlify.com/docs/3.0/tasks/monitor/key-metrics/

**Comment by dcalvin** [comment]
> @dcalvin Can you have a try with https://deploy-preview-114--tikv.netlify.com/docs/3.0/tasks/monitor/key-metrics/

This looks good enough to merge. I like it. And I tested it on phone, looking good too. Thanks.

**Pull request merged**
