### PR TITLE
Fix broken URLs in footer

### PR DESCRIPTION
**Pull request by jarifibrahim**

### CODE REVIEW

**Comment by dcalvin** [comment]
@jarifibrahim Thanks for your PR! Please could you add a DCO for your commit? (using "git commit --amend --signoff")?

**Comment by Hoverbear** [comment]
Unfortunately I'm not allowed to merge this without the DCO signoff. :(

**Comment by jarifibrahim** [comment]
@dcalvin @Hoverbear Done. Please check again.

**Comment by dcalvin** [comment]
> @dcalvin @Hoverbear Done. Please check again.
Thanks for your contribution!

**Comment by Hoverbear** [comment]
@jarifibrahim Thanks so much! :)

**Pull request merged**
