### PR TITLE
Change wording for "Network requirements"

### PR DESCRIPTION
**Pull request by shichun-0415**
### What is changed?
Change wording for "Network requirements"

### Any related PRs or issues?
No

### CODE REVIEW

**Comment by shichun-0415** [comment]
I've finished the self-check of this PR. PTAL @TomShawn

**Review by TomShawn — APPROVED** [review]
LGTM

**Review by iosmanthus — APPROVED** [review]
LGTM

**Review by marsishandsome — APPROVED** [review]
LGTM

**Pull request merged**
